CREATE PROCEDURE CastVote
    @AADHAR_NO NVARCHAR(12),
    @VOTER_ID NVARCHAR(10),
    @VOTE_FOR NVARCHAR(50),
    @OTP INT
AS
BEGIN
    DECLARE @USER_AUTHORIZED_TO_VOTE BIT = 0;
    DECLARE @OVERRIDE_VOTE BIT = 0;

    SELECT @USER_AUTHORIZED_TO_VOTE = 1 FROM AADHAR
    WHERE AADHAR_NO = @AADHAR_NO AND VOTER_ID = @VOTER_ID AND OTP = @OTP;

    IF @USER_AUTHORIZED_TO_VOTE = 1
    BEGIN
        SELECT @OVERRIDE_VOTE = 1 FROM VOTING_RESULT WHERE VOTER_ID = @VOTER_ID;
        IF @OVERRIDE_VOTE = 1
        BEGIN
           UPDATE VOTING_RESULT SET VOTE_FOR = @VOTE_FOR WHERE VOTER_ID = @VOTER_ID;
        END
        ELSE
        BEGIN
           INSERT INTO VOTING_RESULT(VOTER_ID, VOTE_FOR) VALUES(@VOTER_ID, @VOTE_FOR);
        END
    END
END