CREATE PROCEDURE LinkVoterIdToAadhar
    @AADHAR_NO NVARCHAR(12),
    @VOTER_ID NVARCHAR(10),
    @NAME NVARCHAR(50),
    @DOB NVARCHAR(10),
    @FATHER_NAME NVARCHAR(50),
    @GENDER NVARCHAR(10)
AS
BEGIN

DECLARE @OTP_VERIFIED BIT;
DECLARE @LINKED_TO_AADHAR BIT;
DECLARE @VOTER_ID_MATCHED BIT = 0;
DECLARE @LINKING_SUCCESSFUL BIT = 0;

SELECT @OTP_VERIFIED = OTP_VERIFIED FROM AADHAR WHERE AADHAR_NO = @AADHAR_NO;
SELECT @LINKED_TO_AADHAR = LINKED_TO_AADHAR FROM VOTING WHERE VOTER_ID = @VOTER_ID;

IF @OTP_VERIFIED = 1
BEGIN
    IF @LINKED_TO_AADHAR = 0
    BEGIN
        BEGIN TRANSACTION
            UPDATE VOTING
            SET LINKED_TO_AADHAR = 1, @VOTER_ID_MATCHED = 1
            WHERE VOTER_ID = @VOTER_ID AND NAME = @NAME AND FATHER_NAME = @FATHER_NAME AND GENDER = @GENDER AND DOB = @DOB;

            IF @VOTER_ID_MATCHED = 1
            BEGIN
                UPDATE AADHAR
                SET VOTER_ID = @VOTER_ID, @LINKING_SUCCESSFUL = 1
                WHERE AADHAR_NO = @AADHAR_NO;
            END

            IF @LINKING_SUCCESSFUL = 1
            BEGIN
                SELECT 'SuccessfullyLinked' AS VOTER_ID_LINKING_STATUS;
            END
            ELSE
            BEGIN
                SELECT 'LinkingFailed' AS VOTER_ID_LINKING_STATUS;
            END
        COMMIT
    END
    ELSE
    BEGIN
        SELECT 'AlreadyLinked' AS VOTER_ID_LINKING_STATUS;
    END
END
ELSE
BEGIN
    SELECT 'Unauthorized' AS VOTER_ID_LINKING_STATUS;
END
END