CREATE PROCEDURE LinkVoterIdToAadhar
    @AADHAR_NO NVARCHAR(12),
    @VOTER_ID NVARCHAR(10),
    @NAME NVARCHAR(50),
    @DOB NVARCHAR(10),
    @FATHER_NAME NVARCHAR(50),
    @GENDER NVARCHAR(10),
    @OTP INT
AS
BEGIN

DECLARE @OTP_VERIFIED BIT = 0;
DECLARE @LINKED_TO_AADHAR BIT = 0;
DECLARE @VOTER_ID_MATCHED BIT = 0;
DECLARE @LINKING_SUCCESSFUL BIT = 0;
DECLARE @IDENTITY_MATCHED BIT = 0;

SELECT * INTO #AADHAR_TEMP FROM AADHAR WHERE AADHAR_NO = @AADHAR_NO;
SELECT * INTO #VOTING_TEMP FROM VOTING WHERE VOTER_ID = @VOTER_ID;

SELECT @OTP_VERIFIED = CASE WHEN @OTP = OTP THEN 1 ELSE 0 END FROM #AADHAR_TEMP;
SELECT @LINKED_TO_AADHAR = LINKED_TO_AADHAR FROM #VOTING_TEMP;

IF @OTP_VERIFIED = 1
BEGIN
    IF @LINKED_TO_AADHAR = 0
    BEGIN
        BEGIN TRANSACTION
            SELECT @IDENTITY_MATCHED = 1 FROM #AADHAR_TEMP a
            CROSS JOIN #VOTING_TEMP v
            WHERE a.NAME = v.NAME OR a.FATHER_NAME = v.FATHER_NAME OR a.DOB = v.dob;

            IF @IDENTITY_MATCHED = 1
            BEGIN
                UPDATE VOTING
                SET LINKED_TO_AADHAR = 1, @VOTER_ID_MATCHED = 1
                WHERE VOTER_ID = @VOTER_ID AND NAME = @NAME AND FATHER_NAME = @FATHER_NAME AND GENDER = @GENDER AND DOB = @DOB;

                IF @VOTER_ID_MATCHED = 1
                BEGIN
                    UPDATE AADHAR
                    SET VOTER_ID = @VOTER_ID, @LINKING_SUCCESSFUL = 1
                    WHERE AADHAR_NO = @AADHAR_NO;
                END

                IF @LINKING_SUCCESSFUL = 1
                BEGIN
                    SELECT 'SuccessfullyLinked' AS VOTER_ID_LINKING_STATUS;
                END
                ELSE
                BEGIN
                    SELECT 'LinkingFailed' AS VOTER_ID_LINKING_STATUS;
                END
            END
            ELSE
            BEGIN
                SELECT 'LinkingFailed' AS VOTER_ID_LINKING_STATUS;
            END
        COMMIT
    END
    ELSE
    BEGIN
        SELECT 'AlreadyLinked' AS VOTER_ID_LINKING_STATUS;
    END
END
ELSE
BEGIN
    SELECT 'Unauthorized' AS VOTER_ID_LINKING_STATUS;
END

DROP TABLE #AADHAR_TEMP;
DROP TABLE #VOTING_TEMP;

END
