CREATE PROCEDURE VerifyOtp
    @AADHAR_NO NVARCHAR(12),
    @OTP INT
AS
BEGIN
    UPDATE AADHAR
    SET OTP_VERIFIED = 1
    WHERE AADHAR_NO = @AADHAR_NO AND OTP = @OTP;
    SELECT @@ROWCOUNT AS NO_OF_ROWS_AFFECTED;
END;