CREATE PROCEDURE VerifyOtp
    @AADHAR_NO NVARCHAR(12),
    @OTP INT
AS
BEGIN
    DECLARE @OTP_VERIFIED BIT = 0;
    UPDATE AADHAR
    SET OTP_VERIFIED = 1, @OTP_VERIFIED = 1
    WHERE AADHAR_NO = @AADHAR_NO AND OTP = @OTP;
    SELECT @OTP_VERIFIED AS OTP_VERIFIED;
END;