CREATE PROCEDURE VerifyOtp
    @AADHAR_NO NVARCHAR(12),
    @OTP INT
AS
BEGIN
    DECLARE @OTP_VERIFIED BIT = 0;
    SELECT @OTP_VERIFIED = CASE WHEN AADHAR_NO = @AADHAR_NO AND OTP = @OTP THEN 1 ELSE 0 END FROM AADHAR;
    SELECT @OTP_VERIFIED AS OTP_VERIFIED;
END;